const DURATION_MOVIES = 40;

const EXTRO_LARGE_SIZE = 1325;
const LARGE_SIZE = 1027;
const MEDIUM_SIZE = 655;

const DISPLAY_MOVIES_LARGE_SIZE = 12;
const DISPLAY_MOVIES_MEDIUM_SIZE = 8;
const DISPLAY_MOVIES_SMALL_SIZE = 5;

const ADD_MOVIES_EXTRO_LARGE_SIZE = 4;
const ADD_MOVIES_LARGE_SIZE = 3;
const ADD_MOVIES_MEDIUM_SIZE = 2;
const ADD_MOVIES_SMALL_SIZE = 2;

export {
  DURATION_MOVIES,
  EXTRO_LARGE_SIZE,
  LARGE_SIZE,
  MEDIUM_SIZE,
  DISPLAY_MOVIES_LARGE_SIZE,
  DISPLAY_MOVIES_MEDIUM_SIZE,
  DISPLAY_MOVIES_SMALL_SIZE,
  ADD_MOVIES_EXTRO_LARGE_SIZE,
  ADD_MOVIES_LARGE_SIZE,
  ADD_MOVIES_MEDIUM_SIZE,
  ADD_MOVIES_SMALL_SIZE,
};
